#cloud-config
# vim: syntax=yaml
package_update: true
package_upgrade: true
hostname: workstation
fqdn: workstation.example.com
prefer_fqdn_over_hostname: true
power_state:
  mode: reboot
package_reboot_if_required: True
ssh_pwauth: true
password: ubuntu
apt:
  sources:
      kubernetes:
          source: "deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main"
          keyid: "B53DC80D13EDEF05"
      docker: 
          source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
          keyid: "8D81803C0EBFCD88"
      github-cli:
          source: "deb [arch=amd64] https://cli.github.com/packages stable main"
          keyid: "23F3D4EA75716059"
      hashicorp:
          source: "deb [signed-by=$KEY_FILE] https://apt.releases.hashicorp.com jammy main"
          keyid: "AA16FCBCA621E701"
byobu_by_default: enable-system
system_info:
  default_user:
    name: ubuntu
    home: /home/ubuntu
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/zsh
    groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev, libvirtd, docker]
users:
  - default
packages:
  - qemu-guest-agent
  - vim
  - git
  - zsh
  - software-properties-common
  - gnupg2
  - curl
  - apt-transport-https 
  - gnupg-agent
  - ca-certificates
  - lsb-release
  - bash-completion
  - wget
  - jq
  - yamllint
  - moreutils
  - python3-sphinx
  - python3-pip
  - python3.9
  - build-essential
  - fonts-powerline
  - powerline
  - fzf
  - speedtest-cli
  - kubectl
  - docker-ce
  - gh
  - terraform
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, qemu-guest-agent ]
  - [ systemctl, start, qemu-guest-agent ]
  - [ systemctl, restart, systemd-sysctl ]
  - systemctl enable docker
  - systemctl start docker
  - curl -LO "https://vesio.azureedge.net/releases/vesctl/$(curl -s https://downloads.volterra.io/releases/vesctl/latest.txt)/vesctl.linux-amd64.gz"
  - gunzip vesctl.linux-amd64.gz
  - mv vesctl.linux-amd64 /usr/local/bin/vesctl
  - chown root:root /usr/local/bin/vesctl
  - chmod 755 /usr/local/bin/vesctl
  - vesctl completion bash > /etc/bash_completion.d/vesctl > /dev/null
  - pip3 install sphobjinv
  - 'usermod -u 502 ubuntu'
  - 'groupmod -g 20 ubuntu'
write_files:
  - path: /etc/sysctl.d/10-disable-ipv6.conf
    permissions: '0644'
    owner: root
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
ansible:
  install_method: distro
  package_name: ansible
  run_user: ubuntu
  galaxy:
    actions:
      - ["ansible-galaxy", "install", "gantsign.oh-my-zsh"]
  pull:
    url: "https://github.com/robinmordasiewicz/linux-userland.git"
    playbook_name: "userland.yml"
